# Generated by Django 5.2.7 on 2025-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "mangadex_id",
                    models.CharField(
                        help_text="The MangaDex UUID", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Series",
            },
        ),
    ]
